# Generated by Django 5.0.6 on 2026-08-28 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0008_client_faena_company_client_role'),
        ('orders', '0012_alter_missingitemresolution_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeighIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Ref')),
                ('garment_count', models.PositiveIntegerField(verbose_name='Prendas contadas en báscula')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso del morral (kg)')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de digitalizar'), ('DIGITALIZADA', 'Digitalizada'), ('ANULADA', 'Anulada')], db_index=True, default='PENDIENTE', max_length=15)),
                ('weighed_at', models.DateTimeField(db_index=True, verbose_name='Momento del pesaje')),
                ('digitized_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weigh_ins', to='companies.client', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weigh_ins', to='companies.company', verbose_name='Empresa')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weigh_in', to='orders.laundryorder', verbose_name='Guía digitalizada')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('weighed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pesaje',
                'verbose_name_plural': 'Pesajes',
                'ordering': ['-weighed_at'],
            },
        ),
        migrations.CreateModel(
            name='WeighLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='N° de prenda dentro del morral')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='Pistoleada en empaque')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('weigh_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='weighing.weighin')),
            ],
            options={
                'verbose_name': 'Etiqueta de prenda',
                'verbose_name_plural': 'Etiquetas de prenda',
                'ordering': ['weigh_in', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='weighin',
            index=models.Index(fields=['status', 'weighed_at'], name='weigh_status_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='weighlabel',
            constraint=models.UniqueConstraint(fields=('weigh_in', 'sequence'), name='weigh_label_unique_sequence'),
        ),
    ]
