# Generated by Django 5.0.6 on 2026-09-28 17:46

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de sincronización',
                'verbose_name_plural': 'Estado de sincronización',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=64)),
                ('row_id', models.BigIntegerField()),
                ('op', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Cambio pendiente',
                'verbose_name_plural': 'Cambios pendientes',
                'db_table': 'sync_changelog',
                'indexes': [models.Index(fields=['created_at'], name='sync_changelog_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pull_cursor', models.BigIntegerField(default=0)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_pull_at', models.DateTimeField(blank=True, null=True)),
                ('reported_pending', models.PositiveIntegerField(default=0)),
                ('service_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sync_node', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servidor local',
                'verbose_name_plural': 'Servidores locales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DESCARTADO', 'Edición descartada'), ('RENOMBRADO', 'Nombre duplicado renombrado'), ('DUPLICADO', 'Registro duplicado eliminado'), ('ERROR', 'Error al aplicar')], max_length=12)),
                ('table', models.CharField(max_length=64)),
                ('row_id', models.BigIntegerField()),
                ('detail', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia de sincronización',
                'verbose_name_plural': 'Incidencias de sincronización',
                'ordering': ['-created_at'],
            },
        ),
    ]
