# Generated by Django 5.0.6 on 2026-07-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=15, verbose_name='RUT empresa')),
                ('billing_type', models.CharField(choices=[('PRENDAS', 'Por prenda'), ('KILOS', 'Por kilo')], default='PRENDAS', max_length=10)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('logo_key', models.CharField(blank=True, max_length=255, verbose_name='Objeto S3 del logo')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
    ]
