# Generated by Django 5.0.6 on 2026-07-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='delivery_flow',
            field=models.CharField(choices=[('FLUJO_1', 'Flujo 1 - entrega en habitación'), ('FLUJO_2', 'Flujo 2 - entrega solo al cliente')], default='FLUJO_1', max_length=10, verbose_name='Modalidad de entrega'),
        ),
        migrations.AddField(
            model_name='company',
            name='reference_prefix',
            field=models.CharField(blank=True, help_text='Inicial de faena/empresa que antecede al correlativo semanal del ref (ej. "P" en P1238).', max_length=3, verbose_name='Prefijo del ref'),
        ),
    ]
