# Generated by Django 5.0.6 on 2026-08-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_client_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='service_type',
            field=models.CharField(choices=[('PERSONAL', 'Ropa de trabajador'), ('HOTELERIA', 'Lencería de hotelería')], default='PERSONAL', max_length=10, verbose_name='Tipo de servicio'),
        ),
    ]
