# Generated by Django 5.0.6 on 2026-08-11 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camps', '0001_initial'),
        ('companies', '0006_company_service_type'),
        ('garments', '0002_remove_garmenttype_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinenBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('batch_number', models.CharField(max_length=20, unique=True, verbose_name='N° de lote')),
                ('status', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En proceso'), ('DESPACHADO', 'Despachado')], db_index=True, default='RECIBIDO', max_length=12)),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='Recepción de la carga')),
                ('promised_at', models.DateTimeField(blank=True, null=True, verbose_name='Devolución comprometida')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='Despacho de vuelta a faena')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso total (kg)')),
                ('observations', models.TextField(blank=True)),
                ('received_by_client', models.CharField(blank=True, max_length=100, verbose_name='Recibido en faena por')),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linen_batches', to='camps.camp')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linen_batches', to='companies.company')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de hotelería',
                'verbose_name_plural': 'Lotes de hotelería',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='LinenBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=60, verbose_name='Lencería fuera de catálogo')),
                ('quantity_in', models.PositiveIntegerField(verbose_name='Cantidad recibida')),
                ('quantity_out', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad devuelta')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso de esta lencería (kg)')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hospitality.linenbatch')),
                ('garment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='garments.garmenttype')),
            ],
            options={
                'verbose_name': 'Línea de lote',
                'verbose_name_plural': 'Líneas de lote',
            },
        ),
        migrations.AddIndex(
            model_name='linenbatch',
            index=models.Index(fields=['status', 'received_at'], name='hospitality_status_790247_idx'),
        ),
        migrations.AddIndex(
            model_name='linenbatch',
            index=models.Index(fields=['company', 'status'], name='hospitality_company_419336_idx'),
        ),
        migrations.AddConstraint(
            model_name='linenbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'garment_type'), name='unique_garment_type_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='linenbatchitem',
            constraint=models.CheckConstraint(check=models.Q(('garment_type__isnull', False), models.Q(('custom_name', ''), _negated=True), _connector='OR'), name='batch_item_has_garment_type_or_custom_name'),
        ),
    ]
