# Generated by Django 5.0.6 on 2026-07-20 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('garments', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='N° OT')),
                ('ticket_number', models.CharField(blank=True, max_length=20)),
                ('shift', models.CharField(blank=True, max_length=10, verbose_name='Turno')),
                ('status', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_LAVADO', 'En lavado'), ('EN_REVISION', 'En revisión'), ('INCOMPLETA', 'Incompleta'), ('COMPLETADA', 'Completada'), ('DESPACHADA', 'Despachada'), ('ENTREGADA', 'Entregada'), ('COBRADA', 'Cobrada')], db_index=True, default='RECIBIDA', max_length=15)),
                ('garment_count', models.PositiveIntegerField(default=0)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('promised_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('billed_at', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=20)),
                ('control_code', models.CharField(blank=True, max_length=20)),
                ('photo_key', models.CharField(blank=True, max_length=255, verbose_name='Objeto S3 de la foto')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='companies.company')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('weighed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Guía',
                'verbose_name_plural': 'Guías',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='garments.garmenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.laundryorder')),
            ],
            options={
                'verbose_name': 'Detalle de guía',
                'verbose_name_plural': 'Detalles de guía',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_LAVADO', 'En lavado'), ('EN_REVISION', 'En revisión'), ('INCOMPLETA', 'Incompleta'), ('COMPLETADA', 'Completada'), ('DESPACHADA', 'Despachada'), ('ENTREGADA', 'Entregada'), ('COBRADA', 'Cobrada')], max_length=15)),
                ('new_status', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_LAVADO', 'En lavado'), ('EN_REVISION', 'En revisión'), ('INCOMPLETA', 'Incompleta'), ('COMPLETADA', 'Completada'), ('DESPACHADA', 'Despachada'), ('ENTREGADA', 'Entregada'), ('COBRADA', 'Cobrada')], max_length=15)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.laundryorder')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='laundryorder',
            index=models.Index(fields=['status', 'received_at'], name='orders_laun_status_04c92a_idx'),
        ),
        migrations.AddIndex(
            model_name='laundryorder',
            index=models.Index(fields=['company', 'status'], name='orders_laun_company_64d64d_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'garment_type'), name='unique_garment_type_per_order'),
        ),
    ]
