# Generated by Django 5.0.6 on 2026-07-21 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=3)),
                ('iso_year', models.PositiveSmallIntegerField()),
                ('iso_week', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'Correlativo de ref',
                'verbose_name_plural': 'Correlativos de ref',
            },
        ),
        migrations.CreateModel(
            name='SiteScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RECEPCION_SUCIA', 'Recepción ropa sucia en faena'), ('RECEPCION_LIMPIA', 'Recepción ropa limpia en faena'), ('ENTREGA', 'Entrega en habitación')], max_length=20)),
                ('scanned_code', models.CharField(db_index=True, max_length=30, verbose_name='Código pistoleado')),
                ('scanned_at', models.DateTimeField(db_index=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Pistoleo en faena',
                'verbose_name_plural': 'Pistoleos en faena',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField()),
                ('device_updated_at', models.DateTimeField(verbose_name='Versión que traía el dispositivo')),
                ('server_updated_at', models.DateTimeField(verbose_name='Versión que tenía el servidor')),
                ('discarded_payload', models.JSONField(verbose_name='Datos descartados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Conflicto de sincronización',
                'verbose_name_plural': 'Conflictos de sincronización',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='laundry_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recepción ropa sucia en lavandería'),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Empaque validado por pistoleo'),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='packed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='site_clean_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recepción ropa limpia en faena'),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='site_clean_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='site_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recepción ropa sucia en faena'),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='site_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Prenda fuera de catálogo'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='scanned_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Prendas pistoleadas al empacar'),
        ),
        migrations.AlterField(
            model_name='laundryorder',
            name='control_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='laundryorder',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='garment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='garments.garmenttype'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('garment_type__isnull', False), models.Q(('custom_name', ''), _negated=True), _connector='OR'), name='item_has_garment_type_or_custom_name'),
        ),
        migrations.AddConstraint(
            model_name='referencecounter',
            constraint=models.UniqueConstraint(fields=('prefix', 'iso_year', 'iso_week'), name='unique_reference_counter_week'),
        ),
        migrations.AddField(
            model_name='sitescan',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_scans', to='orders.laundryorder'),
        ),
        migrations.AddField(
            model_name='sitescan',
            name='scanned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncconflict',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_conflicts', to='orders.laundryorder'),
        ),
        migrations.AddField(
            model_name='syncconflict',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sitescan',
            index=models.Index(fields=['kind', 'scanned_at'], name='orders_site_kind_7ee177_idx'),
        ),
    ]
