# Generated by Django 5.0.6 on 2026-07-22 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remap_legacy_statuses(apps, schema_editor):
    """DESPACHADA y EN_LAVADO se eliminan del modelo (ver OrderStatus en models.py):
    ninguna guía real pasa por ellos hoy usando este sistema (son datos del
    import legado de Access, sin `packed_at` ni recepción en faena registrados),
    así que se remapean al estado más cercano del esquema nuevo antes de que
    esos valores dejen de existir como choices válidos."""
    LaundryOrder = apps.get_model('orders', 'LaundryOrder')
    LaundryOrder.objects.filter(status='DESPACHADA').update(status='COMPLETADA')
    LaundryOrder.objects.filter(status='EN_LAVADO').update(status='RECIBIDA')

    OrderStatusHistory = apps.get_model('orders', 'OrderStatusHistory')
    OrderStatusHistory.objects.filter(previous_status='DESPACHADA').update(previous_status='COMPLETADA')
    OrderStatusHistory.objects.filter(new_status='DESPACHADA').update(new_status='COMPLETADA')
    OrderStatusHistory.objects.filter(previous_status='EN_LAVADO').update(previous_status='RECIBIDA')
    OrderStatusHistory.objects.filter(new_status='EN_LAVADO').update(new_status='RECIBIDA')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_referencecounter_sitescan_syncconflict_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remap_legacy_statuses, noop),
        migrations.RemoveField(
            model_name='laundryorder',
            name='dispatched_at',
        ),
        migrations.RemoveField(
            model_name='laundryorder',
            name='site_clean_received_at',
        ),
        migrations.RemoveField(
            model_name='laundryorder',
            name='site_clean_received_by',
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='incomplete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Guía marcada incompleta al empacar'),
        ),
        migrations.AlterField(
            model_name='laundryorder',
            name='status',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revisión'), ('INCOMPLETA', 'Incompleta'), ('COMPLETADA', 'Completada'), ('ENTREGADA', 'Entregada'), ('COBRADA', 'Cobrada')], db_index=True, default='RECIBIDA', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revisión'), ('INCOMPLETA', 'Incompleta'), ('COMPLETADA', 'Completada'), ('ENTREGADA', 'Entregada'), ('COBRADA', 'Cobrada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revisión'), ('INCOMPLETA', 'Incompleta'), ('COMPLETADA', 'Completada'), ('ENTREGADA', 'Entregada'), ('COBRADA', 'Cobrada')], max_length=15),
        ),
        migrations.CreateModel(
            name='MissingItemResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_type', models.CharField(choices=[('ENCONTRADA', 'Encontrada'), ('COMPRADA', 'Comprada')], max_length=15)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='orders.orderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_item_resolutions', to='orders.laundryorder')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resolución de prenda faltante',
                'verbose_name_plural': 'Resoluciones de prenda faltante',
                'ordering': ['-resolved_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='missingitemresolution',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('resolution_type', 'COMPRADA'), _negated=True), ('purchase_cost__isnull', False), _connector='OR'), name='purchase_requires_cost'),
        ),
    ]
