# Generated by Django 5.0.6 on 2026-07-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_laundryorder_dispatched_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryorder',
            name='weighed_by',
        ),
    ]
