# Generated by Django 5.0.6 on 2026-07-23 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_delivery_flow_company_reference_prefix'),
        ('orders', '0004_remove_laundryorder_weighed_by'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='laundryorder',
            index=models.Index(fields=['incomplete_at'], name='ord_incomplete_at_idx'),
        ),
        migrations.AddIndex(
            model_name='laundryorder',
            index=models.Index(fields=['completed_at'], name='ord_completed_at_idx'),
        ),
        migrations.AddIndex(
            model_name='laundryorder',
            index=models.Index(fields=['delivered_at'], name='ord_delivered_at_idx'),
        ),
        migrations.AddIndex(
            model_name='missingitemresolution',
            index=models.Index(fields=['resolved_at'], name='mir_resolved_at_idx'),
        ),
        migrations.AddIndex(
            model_name='missingitemresolution',
            index=models.Index(fields=['resolution_type'], name='mir_res_type_idx'),
        ),
    ]
