# Generated by Django 5.0.6 on 2026-07-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_drop_unit_price_laundryorder_billed_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='N° OT'),
        ),
    ]
