# Generated by Django 5.0.6 on 2026-07-24 18:33

from django.db import migrations, models
from django.db.models import F


def reassign_billed_orders(apps, schema_editor):
    """Retira el estado COBRADA del flujo: las guías que lo tenían ya pasaron
    por su último hito real, así que se reasignan sin cobrarse — ENTREGADA en
    Flujo 1 (usando `billed_at` para rellenar `delivered_at`, que el import
    legado nunca pobló para estas guías: ver import_legacy._build_order) y
    COMPLETADA en Flujo 2 (ese cliente nunca registra entrega individual, y
    `completed_at` ya estaba seteado desde antes de cobrarse).

    Es irreversible a propósito: una vez reasignadas, no hay forma de saber
    cuáles estaban en COBRADA sin guardar un flag aparte, y no vale la pena
    para un estado que se está eliminando.
    """
    LaundryOrder = apps.get_model('orders', 'LaundryOrder')
    db_alias = schema_editor.connection.alias

    flow1_orders = LaundryOrder.objects.using(db_alias).filter(
        status='COBRADA', company__delivery_flow='FLUJO_1',
    )
    flow1_orders.filter(delivered_at__isnull=True).update(status='ENTREGADA', delivered_at=F('billed_at'))
    flow1_orders.filter(delivered_at__isnull=False).update(status='ENTREGADA')

    LaundryOrder.objects.using(db_alias).filter(
        status='COBRADA', company__delivery_flow='FLUJO_2',
    ).update(status='COMPLETADA')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_laundryorder_order_number'),
    ]

    operations = [
        migrations.RunPython(reassign_billed_orders, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='laundryorder',
            name='billed_amount',
        ),
        migrations.RemoveField(
            model_name='laundryorder',
            name='billed_at',
        ),
        migrations.AlterField(
            model_name='laundryorder',
            name='status',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revisión'), ('INCOMPLETA', 'Incompleta'), ('COMPLETADA', 'Completada'), ('ENTREGADA', 'Entregada')], db_index=True, default='RECIBIDA', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revisión'), ('INCOMPLETA', 'Incompleta'), ('COMPLETADA', 'Completada'), ('ENTREGADA', 'Entregada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revisión'), ('INCOMPLETA', 'Incompleta'), ('COMPLETADA', 'Completada'), ('ENTREGADA', 'Entregada')], max_length=15),
        ),
    ]
