# Generated by Django 5.0.6 on 2026-07-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_laundryorder_delivery_room_sitescan_room'),
        ('orders', '0008_remove_billed_status'),
    ]

    operations = [
    ]
