# Generated by Django 5.0.6 on 2026-08-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0002_remove_garmenttype_unit_price'),
        ('orders', '0009_merge_20260727_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='label_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Código de etiqueta lavable'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('label_code', ''), _negated=True), fields=('order', 'label_code'), name='unique_label_code_per_order'),
        ),
    ]
