# Generated by Django 5.0.6 on 2026-08-28 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_reference_counter_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingitemresolution',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='orders.orderitem'),
        ),
    ]
