# Generated by Django 5.0.6 on 2026-09-04 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0004_camp_faena_required'),
        ('companies', '0008_client_faena_company_client_role'),
        ('orders', '0012_alter_missingitemresolution_item'),
        ('workers', '0002_worker_current_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Morral despachado a faena'),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laundryorder',
            name='status',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revisión'), ('INCOMPLETA', 'Incompleta'), ('COMPLETADA', 'Completa'), ('DESPACHADA', 'Despachada'), ('ENTREGADA', 'Entregada')], db_index=True, default='RECIBIDA', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revisión'), ('INCOMPLETA', 'Incompleta'), ('COMPLETADA', 'Completa'), ('DESPACHADA', 'Despachada'), ('ENTREGADA', 'Entregada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revisión'), ('INCOMPLETA', 'Incompleta'), ('COMPLETADA', 'Completa'), ('DESPACHADA', 'Despachada'), ('ENTREGADA', 'Entregada')], max_length=15),
        ),
        migrations.AddIndex(
            model_name='laundryorder',
            index=models.Index(fields=['dispatched_at'], name='ord_dispatched_at_idx'),
        ),
    ]
