# Generated by Django 5.0.6 on 2026-09-04 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_backfill_dispatched_legacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='missingitemresolution',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prenda despachada a faena'),
        ),
        migrations.AddField(
            model_name='missingitemresolution',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='missingitemresolution',
            index=models.Index(fields=['order', 'shipped_at'], name='mir_order_shipped_idx'),
        ),
    ]
