# Generated by Django 5.0.6 on 2026-07-20 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('badge_code', models.CharField(max_length=20, verbose_name='Código/credencial')),
                ('full_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=15, verbose_name='RUT')),
                ('camp', models.CharField(blank=True, max_length=30, verbose_name='Campamento/patio')),
                ('room', models.CharField(blank=True, max_length=20, verbose_name='Pieza')),
                ('shift', models.CharField(blank=True, max_length=10, verbose_name='Turno')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Cargo')),
                ('area', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='companies.company')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='workers_wor_company_07e779_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(fields=('company', 'badge_code'), name='unique_badge_code_per_company'),
        ),
    ]
