# Generated by Django 5.0.6 on 2026-09-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0002_remove_garmenttype_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmenttype',
            name='is_linen',
            field=models.BooleanField(default=False, verbose_name='Se usa en hotelería'),
        ),
    ]
