# Generated by Django 5.0.6 on 2026-07-26 23:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_company_client_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camps', to='companies.client')),
            ],
            options={
                'verbose_name': 'Campamento',
                'verbose_name_plural': 'Campamentos',
                'ordering': ['client', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('qr_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código QR de la puerta')),
                ('is_active', models.BooleanField(default=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='camps.camp')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['camp', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='camp',
            index=models.Index(fields=['client', 'is_active'], name='camp_client_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='camp',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='unique_camp_per_client'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['camp', 'is_active'], name='room_camp_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('camp', 'number'), name='unique_room_per_camp'),
        ),
    ]
